services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: node:20-alpine
    container_name: app
    working_dir: /usr/src/app
    command: sh -c "cd /usr/src/app && npm install && npm run start:dev"
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: user
      DATABASE_PASSWORD: secret
      DATABASE_NAME: erp
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  prisma-studio:
    container_name: prisma-studio
    build:
      context: .
      dockerfile: prisma-studio.Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5555:5555"
    volumes:
      - ./prisma:/app/prisma
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  db_data:
